### ISSUE TITLE
change of names in classes and properties

### ISSUE THREAD

**Issue by lucaturchet** [jannahastings/emotion-ontology#3]
Hello,
I hooked your ontology to mine as I use emotions-related concepts. However I see that you have changed all the names of the concepts to some incomprehensible tags (e.g., MF_0000016, MFOEM_000193, etc. ) In this way the link with the original meaning is not apparent. Why did you do so? The ontology is not usable by anybody as when it is imported in Protegè those tags are visualized and not their meaning. Could you please revert the ontology with its original meanings? 
This is a big issue for me because I have relied extensively to your ontology. Hope you can help.

**Comment by jannahastings** [comment]
Hello, apologies I did not see this issue beforehand, but I think you need to change your Protege settings to visualise the labels rather than the IDs.
